version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wsl
  settings:
    govet:
      enable:
        - shadow
    errcheck:
      exclude-functions:
        - (*go.etcd.io/etcd/client/v3.Client).Close
        - (*github.com/lightstar/golib/pkg/storage/mongo.Client).Close
        - (*github.com/lightstar/golib/pkg/storage/redis.Client).Close
        - (*github.com/lightstar/golib/pkg/storage/redis.Conn).Close
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 10
    misspell:
      locale: US
    nlreturn:
      block-size: 3
    nolintlint:
      require-explanation: true
      require-specific: true
    paralleltest:
      ignore-missing: true
    predeclared:
      ignore:
        - min
        - max
    revive:
      confidence: 0
      rules:
        - name: unused-parameter
          disabled: true
    varnamelen:
      ignore-names:
        - fn
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
        - ok bool
    wsl:
      allow-assign-and-anything: true
      allow-cuddle-declarations: true
