// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.3
// source: api/testproto/test.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_api_testproto_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_api_testproto_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_api_testproto_test_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             int32                  `protobuf:"varint,1,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_api_testproto_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_api_testproto_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_api_testproto_test_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_api_testproto_test_proto protoreflect.FileDescriptor

const file_api_testproto_test_proto_rawDesc = "" +
	"\n" +
	"\x18api/testproto/test.proto\x12\ttestproto\"\x15\n" +
	"\x05Input\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\"\x16\n" +
	"\x06Output\x12\f\n" +
	"\x01b\x18\x01 \x01(\x05R\x01b28\n" +
	"\x04Test\x120\n" +
	"\aGetData\x12\x10.testproto.Input\x1a\x11.testproto.Output\"\x00B*Z(github.com/lightstar/golib/api/testprotob\x06proto3"

var (
	file_api_testproto_test_proto_rawDescOnce sync.Once
	file_api_testproto_test_proto_rawDescData []byte
)

func file_api_testproto_test_proto_rawDescGZIP() []byte {
	file_api_testproto_test_proto_rawDescOnce.Do(func() {
		file_api_testproto_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_testproto_test_proto_rawDesc), len(file_api_testproto_test_proto_rawDesc)))
	})
	return file_api_testproto_test_proto_rawDescData
}

var file_api_testproto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_testproto_test_proto_goTypes = []any{
	(*Input)(nil),  // 0: testproto.Input
	(*Output)(nil), // 1: testproto.Output
}
var file_api_testproto_test_proto_depIdxs = []int32{
	0, // 0: testproto.Test.GetData:input_type -> testproto.Input
	1, // 1: testproto.Test.GetData:output_type -> testproto.Output
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_testproto_test_proto_init() }
func file_api_testproto_test_proto_init() {
	if File_api_testproto_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_testproto_test_proto_rawDesc), len(file_api_testproto_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_testproto_test_proto_goTypes,
		DependencyIndexes: file_api_testproto_test_proto_depIdxs,
		MessageInfos:      file_api_testproto_test_proto_msgTypes,
	}.Build()
	File_api_testproto_test_proto = out.File
	file_api_testproto_test_proto_goTypes = nil
	file_api_testproto_test_proto_depIdxs = nil
}
