name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      TEST_CONFIG_ETCD_ENDPOINTS: etcd:2379
      TEST_REDIS_ADDRESS: redis:6379

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      etcd:
        image: bitnami/etcd
        ports:
          - 2379:2379
        env:
          ALLOW_NONE_AUTHENTICATION: yes

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check code with linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Upload report into codecov
        run: bash <(curl -s https://codecov.io/bash)
