name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      TEST_CONFIG_ETCD_ENDPOINTS: localhost:2379
      TEST_REDIS_ADDRESS: localhost:6379

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      etcd:
        image: bitnami/etcd
        ports:
          - 2379:2379
        env:
          ALLOW_NONE_AUTHENTICATION: yes

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Upload report into codecov
        run: bash <(curl -s https://codecov.io/bash)
